### ISSUE TITLE
Port it to a brainslug plugin

### ISSUE THREAD

**Issue by Maschell** [wilm0x42/wii-gc-adapter-inject#4]
Maybe it would be an option to port this to a brainslug module (https://github.com/Chadderz121/brainslug-wii) to have compatibilty with more games?

**Comment by wilm0x42** [comment]
Chadderz himself actually made his own implementation using brainslug. https://github.com/Chadderz121/wup-028-bslug

I'm nonetheless continuing work on this repo because the Smash community is basically guaranteed to want features that might only make sense on a per-game basis, like perhaps lag optimizations.
