### ISSUE TITLE
discontinued / release date?

### ISSUE THREAD

**Issue by neolectron** [wilm0x42/wii-gc-adapter-inject#5]
Hello there,

I was wondering if you had any updates on this.
Is this project discontinued or something ?

I can see your next milestone: "Make things work on USB loaders and whatnot."
what about that ?

Thanks :)

**Comment by wilm0x42** [comment]
Ah, hello
So, I sorta hit a brick wall last year in debugging this stuff and ultimately got a bit too burnt out on it. (debugging stuff in a dormant hacking scene can take a lot out of you :P)
However, I'm returning to it today, starting to retrace my last steps.

Where things left off, the overall functionality was pretty much finished, only needing final polish, except for the one big issue of not working with USB loaders. Turns out, USB loaders make the USB interface a LOT harder to work with in a hack like this, and supporting both USB loaders AND official disc makes things even harder. The main issue that halted everything was that the hack would be working fine on dolphin emulator in every way, but it would crash on console, with no good method of debugging (since I don't have a USB gecko :/)

So yeah, sorry for the unannounced year-long hiatus :P 
We'll find out in the next couple weeks if I'll be able to complete this or not.
(I'll close this issue when I update the readme)

Thanks for taking interest in this project!

**Comment by neolectron** [comment]
Im sorry for re-openning this one, but if you're willing to find a usb-gecko clone, i'll be happy to participate, in terms of money.
Since it look ridiculously hard to do it without a proper debugging method.
Just tell me, we can make it work.
